LAYER_VIEW/Controllers/MantenimientoController.cs
using LAYER_BUSINESS;
using LAYER_ENTITY;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LAYER_VIEW.Controllers
{
    public class MantenimientoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var servicios = MantenimientoBL.ListarMantenimientos();
            return View(servicios);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(Mantenimiento mantenimiento)
        {
            try
            {
                if (!ValidateData(mantenimiento))
                {
                    return View(mantenimiento);
                }
                MantenimientoBL.Agregar(mantenimiento);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(mantenimiento);
            }
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            var mantenimiento = MantenimientoBL.Detalle(id);
            return View(mantenimiento);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var mantenimiento = MantenimientoBL.Detalle(id);
            return View(mantenimiento);
        }

        [HttpPost]
        public ActionResult Editar(Mantenimiento mantenimiento)
        {
            try
            {
                if (!ValidateData(mantenimiento))
                {
                    return View(mantenimiento);
                }

                MantenimientoBL.Editar(mantenimiento);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(mantenimiento);
            }

        }

        [HttpGet]
        public ActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var empleado = MantenimientoBL.Detalle(id.Value);
            return View(empleado);
        }

        [HttpPost]
        public ActionResult Borrar(int id)
        {
            try
            {
                MantenimientoBL.Borrar(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        private bool ValidateData(Mantenimiento mantenimiento)
        {
            if (mantenimiento.IdVehiculo <= 0)
            {
                ModelState.AddModelError("", "Debe ingresar el Vehiculo");
                return false;
            }
            if (mantenimiento.Tarea == null)
            {
                ModelState.AddModelError("", "Debe ingresar la tarea a realizar");
                return false;
            }
            if (mantenimiento.IdEmpleado <= 0)
            {
                ModelState.AddModelError("", "Debe asignar un Empleado");
                return false;
            }
            if (mantenimiento.Valor <= 0)
            {
                ModelState.AddModelError("", "El valor no puede ser menor o igual a cero.");
                return false;
            }

            return true;
        }

    }
}

LAYER_VIEW/Views/Mantenimiento/Borrar.cshtml
@model LAYER_ENTITY.Mantenimiento

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Mantenimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdMantenimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdMantenimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEstFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEstFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPago)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LAYER_VIEW/Views/Mantenimiento/Crear.cshtml
@model LAYER_ENTITY.Mantenimiento

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mantenimiento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdMantenimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdMantenimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdMantenimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarea, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEmpleado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdEmpleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdEmpleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEstFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEstFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEstFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPago)
                    @Html.ValidationMessageFor(model => model.IsPago, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAYER_VIEW/Views/Mantenimiento/Detalle.cshtml
@model LAYER_ENTITY.Mantenimiento

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle</h2>

<div>
    <h4>Mantenimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdMantenimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdMantenimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarea)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarea)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaEstFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaEstFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPago)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPago)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LAYER_VIEW/Views/Mantenimiento/Editar.cshtml
@model LAYER_ENTITY.Mantenimiento

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Mantenimiento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdMantenimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdMantenimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdMantenimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tarea, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tarea, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tarea, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEmpleado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdEmpleado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdEmpleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaIngreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaIngreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaEstFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaEstFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaEstFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPago, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPago)
                    @Html.ValidationMessageFor(model => model.IsPago, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAYER_VIEW/Views/Mantenimiento/Index.cshtml
@model IEnumerable<LAYER_ENTITY.Mantenimiento>

@{
    ViewBag.Title = "Servicios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Servicios</h2>

<p>
    @Html.ActionLink("Nuevo servicio", "Crear", "Mantenimiento", new { @class = "btn btn-success btn-sm" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tarea)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaEstFin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPago)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td hidden>
            @Html.DisplayFor(modelItem => item.IdMantenimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdVehiculo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarea)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdEmpleado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Valor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaIngreso)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaEstFin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPago)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-warning btn-sm" }) |
            @Html.ActionLink("Detalle", "Details", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-primary btn-sm" }) |
            @Html.ActionLink("Borrar", "Delete", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>