LAYER_VIEW/Controllers/VehiculoController.cs
using LAYER_BUSINESS;
using LAYER_ENTITY;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LAYER_VIEW.Controllers
{
    public class VehiculoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var vehiculos = VehiculoBL.ListarVehiculos();
            return View(vehiculos);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(Vehiculo vehiculo)
        {
            try
            {
                if (!ValidateData(vehiculo))
                {
                    return View(vehiculo);
                }

                VehiculoBL.Agregar(vehiculo);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(vehiculo);
            }
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            var vehiculo = VehiculoBL.Detalle(id);
            return View(vehiculo);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var vehiculo = VehiculoBL.Detalle(id);
            return View(vehiculo);
        }

        [HttpPost]
        public ActionResult Editar(Vehiculo vehiculo)
        {
            try
            {
                if (!ValidateData(vehiculo))
                {
                    return View(vehiculo);
                }

                VehiculoBL.Editar(vehiculo);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(vehiculo);
            }

        }

        [HttpGet]
        public ActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var vehiculo = VehiculoBL.Detalle(id.Value);
            return View(vehiculo);
        }

        [HttpPost]
        public ActionResult Borrar(int id)
        {
            try
            {
                VehiculoBL.Borrar(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        private bool ValidateData(Vehiculo vehiculo)
        {

            if (vehiculo.Patente == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Nombre");
                return false;
            }
            if (vehiculo.NroChasis == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }
            if (vehiculo.NroMotor == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }

            if (vehiculo.Marca == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }
            if (vehiculo.Modelo == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }

            if (vehiculo.CantPuertas <=0)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }
            if (vehiculo.TipoVehiculo == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }
            if (vehiculo.TipoCombustible == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }

            if (vehiculo.Cilindrada <= 0)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }
            if (vehiculo.IdEstado <= 0)
            {
                ModelState.AddModelError("", "Debe ingresar el estado");
                return false;
            }
                                 
            return true;
        }

    }
}

LAYER_VIEW/Views/Vehiculo/Borrar.cshtml
@model LAYER_ENTITY.Vehiculo

@{
    ViewBag.Title = "Borrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Borrar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NroChasis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NroChasis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NroMotor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NroMotor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantPuertas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantPuertas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cilindrada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cilindrada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdEstado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEstado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LAYER_VIEW/Views/Vehiculo/Crear.cshtml
@model LAYER_ENTITY.Vehiculo

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NroChasis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroChasis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroChasis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NroMotor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroMotor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroMotor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantPuertas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantPuertas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantPuertas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCombustible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoCombustible, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCombustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cilindrada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cilindrada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cilindrada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEstado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdEstado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAYER_VIEW/Views/Vehiculo/Detalle.cshtml
@model LAYER_ENTITY.Vehiculo

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalle</h2>

<div>
    <h4>Vehiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Patente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NroChasis)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NroChasis)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NroMotor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NroMotor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantPuertas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantPuertas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoVehiculo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoVehiculo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCombustible)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCombustible)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cilindrada)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cilindrada)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdEstado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEstado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LAYER_VIEW/Views/Vehiculo/Editar.cshtml
@model LAYER_ENTITY.Vehiculo

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Vehiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Patente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Patente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Patente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NroChasis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroChasis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroChasis, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NroMotor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NroMotor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NroMotor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CantPuertas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CantPuertas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CantPuertas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoVehiculo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoVehiculo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoVehiculo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCombustible, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoCombustible, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoCombustible, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cilindrada, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cilindrada, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cilindrada, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEstado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdEstado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAYER_VIEW/Views/Vehiculo/Index.cshtml
@model IEnumerable<LAYER_ENTITY.Vehiculo>

@{
    ViewBag.Title = "Vehiculos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vehiculos</h2>

<p>
    @Html.ActionLink("Agregar vehiculo", "Crear", "Vehiculo", new { @class = "btn btn-success btn-sm" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Patente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NroChasis)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NroMotor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CantPuertas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoVehiculo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCombustible)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cilindrada)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdEstado)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td hidden>
            @Html.DisplayFor(modelItem => item.IdVehiculo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Patente)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NroChasis)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NroMotor)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CantPuertas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoVehiculo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoCombustible)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cilindrada)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdEstado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-warning btn-sm" }) |
            @Html.ActionLink("Detalle", "Details", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-primary btn-sm" }) |
            @Html.ActionLink("Borrar", "Delete", new { /* id=item.PrimaryKey */ }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>