LAYER_VIEW/Controllers/EmpleadoController.cs
using LAYER_BUSINESS;
using LAYER_ENTITY;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LAYER_VIEW.Controllers
{
    public class EmpleadoController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var empleados = EmpleadoBL.ListarEmpleados();
            return View(empleados);
        }

        [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Crear(Empleado empleado)
        {
            try
            {
                if (!ValidateData(empleado))
                {
                    return View(empleado);
                }

                EmpleadoBL.Agregar(empleado);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(empleado);
            }
        }

        [HttpGet]
        public ActionResult Detalle(int id)
        {
            var empleado = EmpleadoBL.Detalle(id);
            return View(empleado);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var empleado = EmpleadoBL.Detalle(id);
            return View(empleado);
        }

        [HttpPost]
        public ActionResult Editar(Empleado empleado)
        {
            try
            {
                if (!ValidateData(empleado))
                {
                    return View(empleado);
                }

                EmpleadoBL.Editar(empleado);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(empleado);
            }

        }

        [HttpGet]
        public ActionResult Borrar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var empleado = EmpleadoBL.Detalle(id.Value);
            return View(empleado);
        }

        [HttpPost]
        public ActionResult Borrar(int id)
        {
            try
            {
                EmpleadoBL.Borrar(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        private bool ValidateData(Empleado empleado)
        {
            if (empleado.DNI <= 0)
            {
                ModelState.AddModelError("", "Debe ingresar el DNI");
                return false;
            }
            if (empleado.Nombre == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Nombre");
                return false;
            }
            if (empleado.Apellido == null)
            {
                ModelState.AddModelError("", "Debe ingresar el Apellido");
                return false;
            }
            if (empleado.IdEstado == null)
            {
                ModelState.AddModelError("", "Debe ingresar el estado");
                return false;
            }

            return true;
        }

    }
}

LAYER_VIEW/Views/Empleado/Borrar.cshtml
@model LAYER_ENTITY.Empleado

@{
    ViewBag.Title = "Borrar empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Borrar Empleado</h3>

<h3>¿Seguro que quiere borrar el empleado?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt hidden>
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>

        <dd hidden>
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DNI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayName("Estado")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEstado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-1 col-md-4">
                    <input type="submit" value="Borrar" class="btn btn-danger btn-sm" />
                </div>
                <div class="col-md-pull-3 col-md-4">
                    @Html.ActionLink("Regresar", "Index", "Empleado", new { @class = "btn btn-primary btn-sm" })
                </div>
            </div>
        </div>
    }
</div>

LAYER_VIEW/Views/Empleado/Crear.cshtml
@model LAYER_ENTITY.Empleado

@{
    ViewBag.Title = "Crear empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Crear Empleado</h3>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />        
        <div class="form-group">
            @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdEstado, htmlAttributes: new { @class = "control-label col-md-2" }, labelText:"Estado")
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdEstado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdEstado, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-4">
                    <input type="submit" value="Crear" class="btn btn-success btn-sm" />
                </div>
                <div class="col-md-pull-2 col-md-4">
                    @Html.ActionLink("Regresar", "Index", "Empleado", new { @class = "btn btn-primary btn-sm" })
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAYER_VIEW/Views/Empleado/Detalle.cshtml
@model LAYER_ENTITY.Empleado

@{
    ViewBag.Title = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Detalle Empleado</h3>

<div>
    <h4>Empleado</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt hidden>
            @Html.DisplayNameFor(model => model.IdEmpleado)
        </dt>

        <dd hidden>
            @Html.DisplayFor(model => model.IdEmpleado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DNI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DNI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayName("Estado")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdEstado)
        </dd>

    </dl>
</div>
<div class="row">
    <div class="form-group">
        <div class="col-md-offset-1 col-md-4">
            @Html.ActionLink("Editar", "Editar", new { id = Model.IdEmpleado }, new { @class = "btn btn-warning btn-sm" }) 
        </div>
        <div class="col-md-pull-3 col-md-4">
            @Html.ActionLink("Regresar", "Index", "Empleado", new { @class = "btn btn-primary btn-sm" })
        </div>
    </div>
</div>

LAYER_VIEW/Views/Empleado/Editar.cshtml
@model LAYER_ENTITY.Empleado

@{
    ViewBag.Title = "Editar empleado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h3>Editar Empleado</h3>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" hidden>
        @Html.LabelFor(model => model.IdEmpleado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdEmpleado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdEmpleado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DNI, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DNI, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DNI, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IdEstado, htmlAttributes: new { @class = "control-label col-md-2" }, labelText: "Estado")
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdEstado, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdEstado, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <div class="col-md-offset-1 col-md-4">
                <input type="submit" value="Guardar" class="btn btn-warning btn-sm" />
            </div>
            <div class="col-md-pull-1 col-md-4">
                @Html.ActionLink("Regresar", "Index", "Empleado", new { @class = "btn btn-primary btn-sm" })
            </div>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LAYER_VIEW/Views/Empleado/Index.cshtml
@model IEnumerable<LAYER_ENTITY.Empleado>

@{
    ViewBag.Title = "Listado de Empleados";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Listado de Empleados</h3>

<p>
    @Html.ActionLink("Nuevo", "Crear", "Empleado", new { @class = "btn btn-success btn-sm" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DNI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            Estado
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td hidden>
            @Html.DisplayFor(modelItem => item.IdEmpleado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DNI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdEstado)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new {  id=item.IdEmpleado  }, new { @class = "btn btn-warning btn-sm" }) |
            @Html.ActionLink("Detalle", "Detalle", new {  id=item.IdEmpleado  }, new { @class = "btn btn-primary btn-sm" }) |
            @Html.ActionLink("Borrar", "Borrar", new {  id=item.IdEmpleado  }, new { @class = "btn btn-danger btn-sm" })
        </td>
    </tr>
}

</table>